name: very_good_hub
description: A very good hub where unicorns meet
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: packages/api_client
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  hub_domain:
    path: api/packages/hub_domain
  intl: ^0.18.0
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
