name: authentication_repository
description: Repository with authentication features
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  api_client:
    path: ../api_client
  hub_domain:
    path: ../../api/packages/hub_domain
  mocktail: ^0.3.0
  rxdart: ^0.27.7
  test: ^1.19.2
  very_good_analysis: ^5.0.0
