name: very_good_hub_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.3.0
  db_client:
    path: packages/db_client
  hub_domain:
    path: packages/hub_domain
  session_repository:
    path: packages/session_repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
